name: Check clang-format
on: [push, pull_request]
jobs:
  check-clang-format:
    name: Check clang-format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jidicula/clang-format-action@v4.14.0
      with:
        clang-format-version: '19'
        check-path: './src'
